/**
 * Weekly / monthly executive reports generated by the AI CEO.
 */

import type { CompanyHealthSnapshot, ExecutiveReport, ExecutiveReportPeriod, KpiHistoryPoint, OperationalRisk } from "./types";
import { newId, nowIso } from "../workspace/json-file";
import { sanitizeCeoText } from "./safety";

export function buildExecutiveReport(input: {
  workspaceId: string;
  period: ExecutiveReportPeriod;
  health: CompanyHealthSnapshot;
  previousHealth: CompanyHealthSnapshot | null;
  kpiHistory: KpiHistoryPoint[];
  risks: OperationalRisk[];
  achievements: string[];
  failures: string[];
  learningNotes: string[];
  now?: string;
}): ExecutiveReport {
  const now = input.now ?? nowIso();
  const periodLabel =
    input.period === "weekly"
      ? `Week of ${now.slice(0, 10)}`
      : `Month of ${now.slice(0, 7)}`;

  const kpiChanges = buildKpiChanges(input.previousHealth, input.health);
  const trends = [
    `Company health is ${input.health.label} at ${input.health.score}%.`,
    input.kpiHistory.length >= 2
      ? `Health moved from ${input.kpiHistory[input.kpiHistory.length - 2]?.score ?? "—"} to ${input.health.score}.`
      : "Not enough history yet for a multi-period trend.",
    `Open operational risks: ${input.risks.filter((r) => r.status === "open").length}.`,
  ];

  const recommendations = [
    ...input.risks
      .filter((r) => r.severity === "critical" || r.severity === "high")
      .slice(0, 4)
      .map((r) => r.recommendation),
    "Keep human approval for all external writes.",
    "Clear the approval queue before expanding new missions.",
  ].slice(0, 8);

  const summary = sanitizeCeoText(
    `${periodLabel}: health ${input.health.score}% (${input.health.label}). ` +
      `${input.achievements.length} achievements, ${input.failures.length} failures recorded. ` +
      `AI CEO recommends focus on approvals and overloaded employees — never auto-writes.`
  );

  return {
    id: newId("execrpt"),
    workspaceId: input.workspaceId,
    period: input.period,
    periodLabel,
    generatedAt: now,
    achievements: input.achievements.map(sanitizeCeoText).slice(0, 12),
    failures: input.failures.map(sanitizeCeoText).slice(0, 12),
    trends: trends.map(sanitizeCeoText),
    recommendations: recommendations.map(sanitizeCeoText),
    kpiChanges,
    operationalRisks: input.risks.slice(0, 10).map((r) => `${r.severity}: ${r.title}`),
    learningProgress: input.learningNotes.map(sanitizeCeoText).slice(0, 8),
    summary,
  };
}

function buildKpiChanges(
  prev: CompanyHealthSnapshot | null,
  curr: CompanyHealthSnapshot
): ExecutiveReport["kpiChanges"] {
  if (!prev) {
    return Object.entries(curr.kpis).map(([kpi, to]) => ({
      kpi,
      from: to,
      to,
      delta: 0,
    }));
  }
  return (Object.keys(curr.kpis) as Array<keyof typeof curr.kpis>).map((kpi) => {
    const from = prev.kpis[kpi];
    const to = curr.kpis[kpi];
    return { kpi, from, to, delta: to - from };
  });
}
